---
title: "NextGen Data Access"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NextGen Data Access}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(dplyr)
library(leaflet)
library(DT)
eval = TRUE

current_version = '05_nextgen'

path = glue::glue('/Volumes/Transcend/ngen/CONUS-hydrofabric/{current_version}')

meta = data.frame(path = list.files(path,full.name = TRUE, pattern = "gpkg$")) %>% 
  filter(!grepl("_ext", path)) %>% 
  filter(!grepl("conus", path)) %>% 
  mutate(file = basename(path),
         v = gsub(".gpkg", "", gsub("nextgen_", "", file)),
         gpkg_link = glue::glue('https://nextgen-hydrofabric.s3.amazonaws.com/{current_version}/nextgen_{v}.gpkg'),
         vpu = paste0("<a href='",gpkg_link,"'>",v,"</a>")) 

vpus = nhdplusTools::get_boundaries() %>%
  filter(VPUID %in% meta$v) %>% 
  sf::st_transform('+proj=longlat +datum=WGS84')
                  
for(i in 1:nrow(meta)){
  t = sf::st_layers(meta$path[i])
  meta$flowpaths[i] =  prettyNum(t$features[which(t$name == "flowpaths")],big.mark=",",scientific=FALSE)
  meta$divides[i] =  prettyNum(t$features[which(t$name == "divides")],big.mark=",",scientific=FALSE)
  meta$hydrolocations[i] =  prettyNum(t$features[which(t$name == "hydrolocations")],big.mark=",",scientific=FALSE)
  meta$nexus[i] =  prettyNum(t$features[which(t$name == "nexus")],big.mark=",",scientific=FALSE)
  meta$size[i] = paste0(round(file.size(meta$path[i]) / 1e6, 2), " Mb")
}

labels = paste("VPU", vpus$VPUID)

pop <- paste(
      paste0('<strong>GPKG: </strong>', meta$vpu ),
      paste("<strong>Flowpath:</strong>", meta$flowpaths),
      paste("<strong>Divides:</strong>", meta$divides),
      paste("<strong>Size:</strong>", meta$size),
      sep = "<br/>"
    )

bbox = as.numeric(sf::st_bbox(vpus))

```




```{r, echo = FALSE, eval = eval}

leaflet(width='100%') %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(data = vpus, 
              fillColor  = "gray", 
              color = "navy",
              fillOpacity = .3,
              weight = 1, 
              label = labels,
              popup = pop,
              highlightOptions = highlightOptions(color = "#FEBC11", weight = 5, bringToFront = FALSE, opacity = 1)) %>% 
  setMaxBounds(lng1 = bbox[1], lng2 = bbox[3], lat1 = bbox[2], lat2 = bbox[4])


```



```{r, echo = FALSE, eval = eval}
library(DT)

getTotal <- function(index, data){

  if(index < 1 || index > ncol(data)){
    return("")
  }  
  
  col <- data[,index]
  col <- gsub("[Mb]","",col)
  col <- suppressWarnings(as.numeric(gsub(",", "", col)))
  if(all(is.na(col))){
    return("Totals")
  } else {
    return(prettyNum(sum(col), big.mark=",",scientific=FALSE))
  }
}

m = meta %>% 
  select(-file, -path, -gpkg_link, -v) 


m = rbind(m, sapply(1:ncol(m), function(x){ getTotal(x, m) }))
m[nrow(m), ncol(m)] = paste0(round(as.numeric(gsub(",", "", m[nrow(m), ncol(m)])) / 1000, 2), " GB")

  DT::datatable(m, escape = FALSE, width="100%",  filter = "none", 
                  rownames = T,
                options = list(autoWidth = T, 
                              pageLength = 25, 
                              scrollCollapse = T,
                              dom = 'lftp',
                              columnDefs = list(list(visible = F, targets = 0)))) %>% 
  DT::formatStyle(0, target = "row", fontWeight = styleEqual(dim(m)[1], "bold"))

  

```