fix_refactor:
	Rscript 02_update_refactor

hydrolocations:
	Rscript 03_update_hydrolocations.R

aggregate:
	Rscript 04_aggregate.R

global_ids:
	Rscript 05_global_id.R
	
nextgen:
	Rscript 06_nextgen.R